# Generated by Django 4.0 on 2025-11-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=10)),
                ('match_played', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('draw_count', models.IntegerField(default=0)),
                ('lose_count', models.IntegerField(default=0)),
                ('goal_scored', models.IntegerField(default=0)),
                ('goal_conceded', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('minutes_played', models.IntegerField()),
                ('goal_scored', models.IntegerField()),
                ('goal_conceded', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('saves', models.IntegerField()),
                ('penalties_saved', models.IntegerField()),
                ('own_goal_scored', models.IntegerField()),
                ('cleansheets', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premier_league.team')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gameweek', models.CharField(max_length=2)),
                ('finished', models.BooleanField()),
                ('kickoff_time', models.DateTimeField()),
                ('team1_score', models.IntegerField(null=True)),
                ('team2_score', models.IntegerField(null=True)),
                ('team1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='premier_league.team')),
                ('team2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='premier_league.team')),
            ],
        ),
    ]
