# Generated by Django 4.0 on 2025-11-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('team_h_score', models.IntegerField()),
                ('team_a_score', models.IntegerField()),
                ('guess_result', models.CharField(max_length=50)),
                ('guess_name', models.CharField(max_length=100)),
                ('fixture_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='premier_league.fixture')),
            ],
        ),
    ]
