# Generated by Django 4.0 on 2025-11-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0003_remove_guess_guess_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='team_a_score',
            new_name='team_1_score',
        ),
        migrations.RenameField(
            model_name='guess',
            old_name='team_h_score',
            new_name='team_2_score',
        ),
    ]
