# Generated by Django 4.0 on 2025-11-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0004_rename_team_a_score_guess_team_1_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
