# Generated by Django 4.0 on 2025-11-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0005_alter_guess_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='fixture_id',
            new_name='fixture',
        ),
    ]
